import {
  Sparkles, Send, RefreshCw, Bot, User, Mic, MicOff,
  FileText, BookOpen, Settings, X, Plus, Trash2, ChevronDown
} from 'lucide-react';
import { useState, useRef, useEffect, useCallback } from 'react';
import { toast } from 'sonner';
import DOMPurify from 'dompurify';
import { api } from '../lib/api';
import { auth } from '../lib/auth';

// ─── Markdown renderer ──────────────────────────────────────────────
function renderMarkdown(text: string): string {
  if (!text) return '';
  let html = text;
  html = html.replace(/```(\w*)\n?([\s\S]*?)```/g, (_: string, _lang: string, code: string) =>
    `<pre><code>${code.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</code></pre>`);
  html = html.replace(/`([^`]+)`/g, (_: string, code: string) => {
    const e = code.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    return `<code>${e}</code>`;
  });
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
  html = html.replace(/^[-*] (.+)$/gm, '<li>$1</li>');
  html = html.replace(/((?:<li>.*<\/li>\n?)+)/g, '<ul>$1</ul>');
  html = html.replace(/\n\n/g, '<br><br>');
  html = html.replace(/\n/g, '<br>');
  html = html.replace(/<br>(<\/?(?:h[1-3]|ul|ol|li|pre)>)/g, '$1');
  html = html.replace(/(<\/?(?:h[1-3]|ul|ol|li|pre)>)<br>/g, '$1');
  return DOMPurify.sanitize(html, { ADD_TAGS: ['h1', 'h2', 'h3', 'code', 'pre'], ADD_ATTR: ['class'] });
}

// ─── Parse [[[ACTION:...]]] tags ─────────────────────────────────────
function parseActions(text: string): { cleanText: string; actions: any[] } {
  const actions: any[] = [];
  const cleanText = text.replace(/\[\[\[ACTION:(.*?)\]\]\]/g, (_: string, actionStr: string) => {
    const parts = actionStr.split(':');
    const type = parts[0];
    const params = parts.slice(1);
    let label = '', icon = '';
    switch (type) {
      case 'alert': icon = '⚡'; label = `Set ${params[0]} alert at $${params[1]}`; break;
      case 'watchlist': icon = '👁️'; label = `Add ${params[0]} to watchlist`; break;
      case 'position': icon = '➕'; label = `Add ${params[1]} ${params[0]} @ $${params[2]}`; break;
      default: return '';
    }
    actions.push({ type, params, label, icon });
    return '';
  });
  return { cleanText, actions };
}

// ─── Parse <<<Q1|||Q2>>> suggestions ────────────────────────────────
function parseSuggestions(text: string): string[] {
  const match = text.match(/<<<(.+?)>>>/);
  if (!match) return [];
  return match[1].split('|||').map(q => q.trim()).filter(Boolean);
}

// ─── PDF export ───────────────────────────────────────────────────────
function exportAsPdf(markdown: string, title = 'AI Analysis') {
  const html = renderMarkdown(markdown);
  const now = new Date();
  const dateStr = now.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  const win = window.open('', '_blank');
  if (!win) { toast.error('Pop-up blocked — please allow pop-ups'); return; }
  win.document.write(`<!DOCTYPE html><html><head><meta charset="utf-8"><title>Portfolio Pro — ${title}</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1a1a1a;padding:40px;max-width:800px;margin:0 auto;line-height:1.6}
.header{border-bottom:2px solid #2962ff;padding-bottom:12px;margin-bottom:24px;display:flex;justify-content:space-between}
.header h1{font-size:20px;color:#2962ff}.date{font-size:12px;color:#666}
h1,h2,h3{margin:12px 0 6px}p,li{font-size:13px;margin-bottom:4px}ul{padding-left:20px;margin-bottom:8px}
table{width:100%;border-collapse:collapse;margin:12px 0;font-size:12px}th,td{border:1px solid #ccc;padding:6px 10px}th{background:#f0f0f0}
pre{background:#f5f5f5;border:1px solid #ddd;border-radius:4px;padding:10px;font-size:12px;margin:8px 0}
code{font-family:monospace;font-size:12px;background:#f0f0f0;padding:1px 4px;border-radius:3px}
.footer{margin-top:32px;padding-top:12px;border-top:1px solid #ddd;font-size:11px;color:#999;text-align:center}
@media print{body{padding:20px}@page{margin:1.5cm}}</style></head><body>
<div class="header"><h1>🧠 Portfolio Pro — ${title}</h1><span class="date">${dateStr}</span></div>
<div>${html}</div>
<div class="footer">Generated by Portfolio Pro Oracle · ${dateStr}</div>
<script>window.onload=function(){window.print()}<\/script></body></html>`);
  win.document.close();
}

// ─── API helpers (raw fetch for SSE) ─────────────────────────────────
async function fetchSSE(path: string, body: any, onChunk: (text: string) => void, onMeta?: (data: any) => void): Promise<{ rawText: string; usage?: any }> {
  const token = auth.getToken();
  const res = await fetch(`/api${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    body: JSON.stringify(body),
  });
  if (res.status === 401) { auth.clearSession(); window.location.href = '/login'; throw new Error('Unauthorized'); }
  if (!res.ok) { const t = await res.text(); throw new Error(t || `HTTP ${res.status}`); }

  const reader = res.body!.getReader();
  const decoder = new TextDecoder();
  let buf = '', rawText = '', usage: any;

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += decoder.decode(value, { stream: true });
    const lines = buf.split('\n');
    buf = lines.pop() || '';
    for (const line of lines) {
      const t = line.trim();
      if (!t.startsWith('data: ')) continue;
      try {
        const d = JSON.parse(t.slice(6));
        if (d.type === 'meta') onMeta?.(d);
        if (d.type === 'chunk' && d.content) { rawText += d.content; onChunk(rawText); }
        if (d.type === 'error') throw new Error(d.error || 'Stream error');
        if (d.type === 'done') usage = d.usage;
      } catch {}
    }
  }
  return { rawText, usage };
}

// ─── Types ─────────────────────────────────────────────────────────────
interface Msg {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  streaming?: boolean;
  actions?: any[];
  usage?: any;
}

interface Provider {
  id: string;
  name: string;
  configured: boolean;
  requiresKey: boolean;
  models?: { id: string; name: string }[];
  modelPreference?: string;
  baseUrl?: string;
  contextLength?: number;
}

interface Conversation {
  id: number;
  title: string;
  updated_at: string;
  created_at: string;
  context?: string;
}

// ─── TypingDots ────────────────────────────────────────────────────────
function TypingDots() {
  return (
    <div className="flex items-center gap-1 py-1">
      {[0, 150, 300].map(d => (
        <span key={d} className="w-2 h-2 bg-purple-500 rounded-full animate-bounce" style={{ animationDelay: `${d}ms` }} />
      ))}
    </div>
  );
}

// ─── MessageBubble ─────────────────────────────────────────────────────
function MessageBubble({ msg, onAction, onPdf }: { msg: Msg; onAction: (action: any) => void; onPdf: (content: string) => void }) {
  const isUser = msg.role === 'user';
  const { cleanText, actions } = msg.role === 'assistant' && !msg.streaming
    ? parseActions(msg.content.replace(/<<<.+?>>>/g, ''))
    : { cleanText: msg.content, actions: [] };

  return (
    <div className={`flex gap-3 ${isUser ? 'flex-row-reverse' : ''} group`}>
      <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
        isUser ? 'bg-gradient-to-br from-blue-500 to-purple-600' : 'bg-gradient-to-br from-purple-500 to-pink-600'
      }`}>
        {isUser ? <User className="w-4 h-4 text-white" /> : <Bot className="w-4 h-4 text-white" />}
      </div>
      <div className={`max-w-[75%] ${isUser ? 'items-end' : 'items-start'} flex flex-col gap-1`}>
        <div className={`px-4 py-3 rounded-xl text-sm leading-relaxed ${
          isUser
            ? 'bg-gradient-to-br from-blue-500/20 to-purple-600/20 border border-blue-500/30 text-white whitespace-pre-wrap'
            : 'bg-gradient-to-br from-[#1a1d29] to-[#14161f] border border-white/10 text-gray-200'
        }`}>
          {msg.streaming ? <TypingDots /> : (
            isUser
              ? msg.content
              : <div dangerouslySetInnerHTML={{ __html: renderMarkdown(cleanText.replace(/<<<.+?>>>/g, '')) }} className="prose-sm prose-invert" />
          )}
        </div>
        {/* Action buttons */}
        {actions.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-1">
            {actions.map((a: any, i: number) => (
              <button key={i} onClick={() => onAction(a)}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-amber-500/10 border border-amber-500/30 rounded-lg text-amber-400 text-xs hover:bg-amber-500/20 transition-colors">
                {a.icon} {a.label}
              </button>
            ))}
          </div>
        )}
        {/* Message actions */}
        {msg.role === 'assistant' && !msg.streaming && msg.content && (
          <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
            <button onClick={() => onPdf(msg.content)}
              className="flex items-center gap-1 px-2 py-1 rounded text-gray-500 hover:text-gray-300 hover:bg-white/5 text-xs transition-colors">
              <FileText className="w-3 h-3" /> PDF
            </button>
            {msg.usage && (
              <span className="text-gray-600 text-xs px-2">{msg.usage.model?.split('/').pop()} · {msg.usage.durationMs ? `${(msg.usage.durationMs/1000).toFixed(1)}s` : ''}</span>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ─── ProviderPanel ──────────────────────────────────────────────────────
function ProviderPanel({ onClose }: { onClose: () => void }) {
  const [providers, setProviders] = useState<Provider[]>([]);
  const [keys, setKeys] = useState<Record<string, string>>({});
  const [urls, setUrls] = useState<Record<string, string>>({});
  const [models, setModels] = useState<Record<string, string>>({});
  const [ollamaModels, setOllamaModels] = useState<{id:string;name:string}[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => { loadProviders(); }, []);

  const loadProviders = async () => {
    try {
      const ps = await (api as any).ai?.providers() || await fetch('/api/ai/providers', { headers: { Authorization: `Bearer ${auth.getToken()}` } }).then(r => r.json());
      setProviders(ps);
      const u: Record<string,string> = {}, m: Record<string,string> = {};
      ps.forEach((p: Provider) => { if (p.baseUrl) u[p.id] = p.baseUrl; if (p.modelPreference) m[p.id] = p.modelPreference; });
      setUrls(u); setModels(m);
    } catch { toast.error('Failed to load providers'); }
    setLoading(false);
  };

  const fetchOllamaModels = async (baseUrl: string) => {
    if (!baseUrl) return;
    try {
      const r = await fetch(`/api/ai/models/ollama?baseUrl=${encodeURIComponent(baseUrl)}`, { headers: { Authorization: `Bearer ${auth.getToken()}` } });
      const d = await r.json();
      if (d.models?.length) setOllamaModels(d.models);
    } catch {}
  };

  const save = async (pid: string) => {
    try {
      const body: any = {};
      if (keys[pid] && !keys[pid].startsWith('••')) body.apiKey = keys[pid];
      if (urls[pid]) body.baseUrl = urls[pid];
      if (models[pid]) body.model = models[pid];
      await fetch(`/api/ai/providers/${pid}/key`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${auth.getToken()}` }, body: JSON.stringify(body) });
      toast.success(`${pid} saved`);
      loadProviders();
    } catch (e: any) { toast.error(e.message); }
  };

  const test = async (pid: string) => {
    try {
      const r = await fetch(`/api/ai/providers/${pid}/test`, { headers: { Authorization: `Bearer ${auth.getToken()}` } });
      const d = await r.json();
      d.success ? toast.success(`✅ ${pid} OK`) : toast.error(`❌ ${d.error || 'Failed'}`);
    } catch (e: any) { toast.error(e.message); }
  };

  const remove = async (pid: string) => {
    if (!confirm(`Remove API key for ${pid}?`)) return;
    try {
      await fetch(`/api/ai/providers/${pid}/key`, { method: 'DELETE', headers: { Authorization: `Bearer ${auth.getToken()}` } });
      toast.success('Key removed'); loadProviders();
    } catch (e: any) { toast.error(e.message); }
  };

  return (
    <div className="fixed inset-0 z-50 flex">
      <div className="flex-1" onClick={onClose} />
      <div className="w-[380px] bg-[#0d0f14] border-l border-white/10 flex flex-col h-full overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-white/10">
          <h3 className="text-white font-semibold">AI Providers</h3>
          <button onClick={onClose} className="text-gray-500 hover:text-white"><X className="w-5 h-5" /></button>
        </div>
        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {loading ? <div className="text-gray-500 text-sm text-center py-8">Loading...</div> : providers.map(p => (
            <div key={p.id} className="bg-[#1a1d29] border border-white/5 rounded-xl p-4 space-y-3">
              <div className="flex items-center gap-2">
                <span>{p.configured ? '✅' : p.requiresKey ? '❌' : '⚡'}</span>
                <span className="text-white font-medium text-sm">{p.name}</span>
              </div>
              {p.requiresKey && (
                <input type="password" placeholder="API Key"
                  value={keys[p.id] || (p.configured ? '••••••••' : '')}
                  onChange={e => setKeys(k => ({...k, [p.id]: e.target.value}))}
                  className="w-full px-3 py-2 bg-[#0d0f14] border border-white/10 rounded-lg text-white text-sm placeholder-gray-600 focus:outline-none focus:border-blue-500/50" />
              )}
              {(p.id === 'ollama' || p.id === 'custom') && (
                <input type="text" placeholder="Base URL (e.g. http://localhost:11434)"
                  value={urls[p.id] || ''}
                  onChange={e => setUrls(u => ({...u, [p.id]: e.target.value}))}
                  onBlur={() => p.id === 'ollama' && fetchOllamaModels(urls[p.id] || '')}
                  className="w-full px-3 py-2 bg-[#0d0f14] border border-white/10 rounded-lg text-white text-sm placeholder-gray-600 focus:outline-none focus:border-blue-500/50" />
              )}
              {p.id === 'custom' && (
                <input type="text" placeholder="Model name"
                  value={models[p.id] || ''}
                  onChange={e => setModels(m => ({...m, [p.id]: e.target.value}))}
                  className="w-full px-3 py-2 bg-[#0d0f14] border border-white/10 rounded-lg text-white text-sm placeholder-gray-600 focus:outline-none focus:border-blue-500/50" />
              )}
              {p.id === 'ollama' && ollamaModels.length > 0 && (
                <select value={models[p.id] || ''} onChange={e => setModels(m => ({...m, [p.id]: e.target.value}))}
                  className="w-full px-3 py-2 bg-[#0d0f14] border border-white/10 rounded-lg text-white text-sm focus:outline-none focus:border-blue-500/50">
                  {ollamaModels.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}
                </select>
              )}
              {p.models && p.models.length > 0 && p.id !== 'ollama' && p.id !== 'custom' && (
                <select value={models[p.id] || p.modelPreference || p.models[0]?.id || ''}
                  onChange={e => setModels(m => ({...m, [p.id]: e.target.value}))}
                  className="w-full px-3 py-2 bg-[#0d0f14] border border-white/10 rounded-lg text-white text-sm focus:outline-none focus:border-blue-500/50">
                  {p.models.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}
                </select>
              )}
              <div className="flex gap-2">
                <button onClick={() => save(p.id)} className="flex-1 px-3 py-1.5 bg-blue-500/20 border border-blue-500/30 rounded-lg text-blue-400 text-xs hover:bg-blue-500/30 transition-colors">💾 Save</button>
                <button onClick={() => test(p.id)} className="px-3 py-1.5 bg-white/5 border border-white/10 rounded-lg text-gray-400 text-xs hover:bg-white/10 transition-colors">🧪 Test</button>
                {p.configured && <button onClick={() => remove(p.id)} className="px-3 py-1.5 bg-red-500/10 border border-red-500/20 rounded-lg text-red-400 text-xs hover:bg-red-500/20 transition-colors">🗑️</button>}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── ConversationsPanel ─────────────────────────────────────────────────
function ConversationsPanel({ currentId, onLoad, onClose }: { currentId?: number; onLoad: (conv: any) => void; onClose: () => void }) {
  const [convs, setConvs] = useState<Conversation[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => { loadConvs(); }, []);

  const loadConvs = async () => {
    try {
      const r = await fetch('/api/ai/conversations', { headers: { Authorization: `Bearer ${auth.getToken()}` } });
      setConvs(await r.json());
    } catch {}
    setLoading(false);
  };

  const del = async (id: number, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!confirm('Delete this conversation?')) return;
    await fetch(`/api/ai/conversations/${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${auth.getToken()}` } });
    setConvs(cs => cs.filter(c => c.id !== id));
  };

  const load = async (id: number) => {
    try {
      const r = await fetch(`/api/ai/conversations/${id}`, { headers: { Authorization: `Bearer ${auth.getToken()}` } });
      const conv = await r.json();
      onLoad(conv);
      onClose();
    } catch (e: any) { toast.error('Failed to load conversation'); }
  };

  return (
    <div className="fixed inset-0 z-50 flex">
      <div className="flex-1" onClick={onClose} />
      <div className="w-[340px] bg-[#0d0f14] border-l border-white/10 flex flex-col h-full">
        <div className="flex items-center justify-between px-5 py-4 border-b border-white/10">
          <h3 className="text-white font-semibold">Conversations</h3>
          <button onClick={onClose} className="text-gray-500 hover:text-white"><X className="w-5 h-5" /></button>
        </div>
        <div className="flex-1 overflow-y-auto">
          {loading ? <div className="text-gray-500 text-sm text-center py-8">Loading...</div> :
           convs.length === 0 ? <div className="text-gray-500 text-sm text-center py-8">No conversations yet</div> :
           convs.map(c => (
            <div key={c.id} onClick={() => load(c.id)}
              className={`flex items-start justify-between p-4 border-b border-white/5 cursor-pointer hover:bg-white/5 transition-colors ${currentId === c.id ? 'bg-white/5' : ''}`}>
              <div className="flex-1 min-w-0">
                <div className="text-white text-sm font-medium truncate">{c.title || 'Untitled'}</div>
                <div className="text-gray-500 text-xs mt-0.5">{new Date(c.updated_at || c.created_at).toLocaleDateString()}</div>
              </div>
              <button onClick={(e) => del(c.id, e)} className="text-gray-600 hover:text-red-400 ml-2 mt-0.5">
                <Trash2 className="w-3.5 h-3.5" />
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ─── Oracle page ────────────────────────────────────────────────────────
export function Oracle() {
  const [messages, setMessages] = useState<Msg[]>([]);
  const [input, setInput] = useState('');
  const [streaming, setStreaming] = useState(false);
  const [conversationId, setConversationId] = useState<number | undefined>(undefined);
  const [contexts, setContexts] = useState<string[]>(['general']);
  const [showProviders, setShowProviders] = useState(false);
  const [showConvs, setShowConvs] = useState(false);
  const [listening, setListening] = useState(false);
  const [providerBadge, setProviderBadge] = useState('');
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [tickerResults, setTickerResults] = useState<any[]>([]);
  const [tickerDropdownOpen, setTickerDropdownOpen] = useState(false);
  const [selectedProvider, setSelectedProvider] = useState(localStorage.getItem('aiProvider') || '');
  const [selectedModel, setSelectedModel] = useState(localStorage.getItem('aiModel') || '');

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const voiceRef = useRef<any>(null);
  const tickerTimerRef = useRef<any>(null);
  const streamingMsgIdRef = useRef<string>('');

  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);
  useEffect(() => { loadProviderBadge(); }, []);

  const loadProviderBadge = async () => {
    try {
      const r = await fetch('/api/ai/providers', { headers: { Authorization: `Bearer ${auth.getToken()}` } });
      const ps: Provider[] = await r.json();
      const configured = ps.filter(p => p.configured || !p.requiresKey);
      if (!configured.length) { setProviderBadge('No provider'); return; }
      let prov = configured.find(p => p.id === selectedProvider);
      if (!prov) { prov = configured.find(p => p.configured) || configured[0]; setSelectedProvider(prov.id); localStorage.setItem('aiProvider', prov.id); }
      const modelId = selectedModel || prov.modelPreference || prov.models?.[0]?.id || '';
      const modelName = prov.models?.find(m => m.id === modelId)?.name || modelId.split('/').pop() || 'default';
      setProviderBadge(`${prov.name} · ${modelName}`);
      if (!selectedModel && modelId) { setSelectedModel(modelId); localStorage.setItem('aiModel', modelId); }
    } catch { setProviderBadge('No provider'); }
  };

  // Voice input
  useEffect(() => {
    const SR = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    if (!SR) return;
    const r = new SR();
    r.continuous = false; r.interimResults = true; r.lang = 'en-US';
    r.onresult = (e: any) => {
      let t = '';
      for (let i = 0; i < e.results.length; i++) t += e.results[i][0].transcript;
      setInput(t);
    };
    r.onend = () => setListening(false);
    r.onerror = (e: any) => {
      setListening(false);
      if (e.error === 'not-allowed') toast.error('Microphone access denied');
    };
    voiceRef.current = r;
  }, []);

  const toggleVoice = () => {
    if (!voiceRef.current) { toast.error('Voice not supported'); return; }
    if (listening) { voiceRef.current.stop(); setListening(false); }
    else { voiceRef.current.start(); setListening(true); }
  };

  // Ticker autocomplete
  const handleInputChange = (val: string) => {
    setInput(val);
    const match = val.match(/\$([A-Za-z]{1,10})$/);
    if (!match) { setTickerDropdownOpen(false); return; }
    clearTimeout(tickerTimerRef.current);
    tickerTimerRef.current = setTimeout(async () => {
      try {
        const res = await api.markets.search(match[1]);
        setTickerResults((res || []).slice(0, 6));
        setTickerDropdownOpen(true);
      } catch { setTickerDropdownOpen(false); }
    }, 200);
  };

  const insertTicker = (symbol: string) => {
    setInput(prev => prev.replace(/\$[A-Za-z]*$/, `$${symbol} `));
    setTickerDropdownOpen(false);
    inputRef.current?.focus();
  };

  // Toggle context chips
  const toggleContext = (ctx: string) => {
    if (ctx === 'general') { setContexts(['general']); return; }
    setContexts(prev => {
      const without = prev.filter(c => c !== 'general');
      const has = without.includes(ctx);
      const next = has ? without.filter(c => c !== ctx) : [...without, ctx];
      return next.length === 0 ? ['general'] : next;
    });
  };

  // Append/update streaming message
  const appendMsg = useCallback((msg: Msg) => {
    setMessages(prev => [...prev, msg]);
  }, []);

  const updateStreamingMsg = useCallback((id: string, content: string) => {
    setMessages(prev => prev.map(m => m.id === id ? { ...m, content, streaming: true } : m));
  }, []);

  const finalizeMsg = useCallback((id: string, content: string, usage?: any) => {
    setMessages(prev => prev.map(m => m.id === id ? { ...m, content, streaming: false, usage } : m));
  }, []);

  // Execute AI action button
  const executeAction = async (action: any) => {
    try {
      const r = await fetch('/api/ai/action', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${auth.getToken()}` }, body: JSON.stringify({ type: action.type, params: action.params }) });
      const d = await r.json();
      d.success ? toast.success(d.message) : toast.error(d.error || 'Action failed');
    } catch (e: any) { toast.error(e.message); }
  };

  // Send chat message
  const send = async (text?: string) => {
    const userText = (text || input).trim();
    if (!userText || streaming) return;
    setInput('');
    setSuggestions([]);

    appendMsg({ id: `u-${Date.now()}`, role: 'user', content: userText, ts: Date.now() } as any);

    const assistantId = `a-${Date.now()}`;
    streamingMsgIdRef.current = assistantId;
    appendMsg({ id: assistantId, role: 'assistant', content: '', streaming: true } as any);
    setStreaming(true);

    try {
      const { rawText, usage } = await fetchSSE(
        '/ai/chat',
        { message: userText, context: contexts.join(','), conversationId, provider: selectedProvider, model: selectedModel },
        (chunk) => updateStreamingMsg(assistantId, chunk),
        (meta) => { if (meta.conversationId) setConversationId(meta.conversationId); }
      );
      finalizeMsg(assistantId, rawText, usage);
      setSuggestions(parseSuggestions(rawText));
      loadProviderBadge();
    } catch (e: any) {
      finalizeMsg(assistantId, `⚠️ ${e.message}`, undefined);
    }
    setStreaming(false);
  };

  // Quick actions
  const quickAction = async (type: string) => {
    if (streaming) return;
    setSuggestions([]);

    let endpoint = '', label = '';
    const autoCtx: string[] = [];

    switch (type) {
      case 'portfolio': endpoint = '/ai/analyze/portfolio'; label = '📊 Review my portfolio'; autoCtx.push('portfolio'); break;
      case 'watchlist': endpoint = '/ai/analyze/watchlist'; label = '👀 Analyze my watchlist'; autoCtx.push('watchlist'); break;
      case 'strategy': endpoint = '/ai/analyze/strategy'; label = '🎯 Suggest trading strategies'; autoCtx.push('portfolio'); break;
      case 'risk': endpoint = '/ai/analyze/risk'; label = '🛡️ Analyze portfolio risk'; autoCtx.push('portfolio'); break;
      case 'onboarding':
        setInput("I'm new here and need help building my first portfolio. Walk me through it step by step — ask me about my goals, risk tolerance, timeline, and budget.");
        setTimeout(() => inputRef.current?.focus(), 50);
        return;
      default: return;
    }

    if (autoCtx.length) setContexts(autoCtx);
    appendMsg({ id: `u-${Date.now()}`, role: 'user', content: label } as any);
    const assistantId = `a-${Date.now()}`;
    appendMsg({ id: assistantId, role: 'assistant', content: '', streaming: true } as any);
    setStreaming(true);

    try {
      const { rawText, usage } = await fetchSSE(
        endpoint, { provider: selectedProvider, model: selectedModel },
        (chunk) => updateStreamingMsg(assistantId, chunk),
        (meta) => { if (meta.conversationId) setConversationId(meta.conversationId); }
      );
      finalizeMsg(assistantId, rawText, usage);
      setSuggestions(parseSuggestions(rawText));
    } catch (e: any) {
      finalizeMsg(assistantId, `⚠️ ${e.message}`, undefined);
    }
    setStreaming(false);
  };

  const newChat = () => {
    setMessages([]);
    setConversationId(undefined);
    setSuggestions([]);
    setContexts(['general']);
    inputRef.current?.focus();
  };

  const loadConversation = (conv: any) => {
    setConversationId(conv.id);
    setMessages((conv.messages || []).map((m: any, i: number) => ({
      id: `loaded-${i}`, role: m.role, content: m.content, streaming: false
    })));
    setSuggestions([]);
  };

  const handleKey = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send(); }
  };

  const exportFullPdf = () => {
    const all = messages.filter(m => !m.streaming);
    if (!all.length) { toast.info('No conversation to export'); return; }
    const md = all.map(m => `**${m.role === 'user' ? 'You' : 'Oracle'}:** ${m.content}`).join('\n\n---\n\n');
    exportAsPdf(md, 'Conversation Export');
  };

  const showWelcome = messages.length === 0;

  return (
    <div className="flex flex-col h-[calc(100vh-73px)] max-w-[1440px] mx-auto">
      {/* Panels */}
      {showProviders && <ProviderPanel onClose={() => { setShowProviders(false); loadProviderBadge(); }} />}
      {showConvs && <ConversationsPanel currentId={conversationId} onLoad={loadConversation} onClose={() => setShowConvs(false)} />}

      {/* Header */}
      <div className="px-6 pt-6 pb-3 flex items-center justify-between flex-wrap gap-3">
        <div className="flex items-center gap-2 min-w-0">
          <Sparkles className="w-5 h-5 text-purple-500 flex-shrink-0" />
          <h2 className="text-xl sm:text-2xl font-bold text-white truncate">Oracle</h2>
          <button onClick={() => setShowProviders(true)} title={providerBadge || 'No AI provider configured'}
            className="flex items-center gap-1 px-2 py-1 bg-white/5 hover:bg-white/10 border border-white/10 rounded-full text-xs text-gray-400 hover:text-white transition-colors flex-shrink-0 max-w-[150px]">
            <ChevronDown className="w-3 h-3 flex-shrink-0" />
            <span className="truncate max-w-[110px]">{providerBadge || 'No AI'}</span>
          </button>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={exportFullPdf} title="Export conversation as PDF" className="p-2 rounded-lg text-gray-500 hover:text-white hover:bg-white/5 transition-colors"><FileText className="w-4 h-4" /></button>
          <button onClick={() => setShowConvs(true)} title="Browse conversations" className="p-2 rounded-lg text-gray-500 hover:text-white hover:bg-white/5 transition-colors"><BookOpen className="w-4 h-4" /></button>
          <button onClick={() => setShowProviders(true)} title="AI settings" className="p-2 rounded-lg text-gray-500 hover:text-white hover:bg-white/5 transition-colors"><Settings className="w-4 h-4" /></button>
          <button onClick={newChat} title="New chat" className="p-2 rounded-lg text-gray-500 hover:text-white hover:bg-white/5 transition-colors"><Plus className="w-4 h-4" /></button>
          <button onClick={newChat} title="Clear chat" className="p-2 rounded-lg text-gray-500 hover:text-white hover:bg-white/5 transition-colors"><RefreshCw className="w-4 h-4" /></button>
        </div>
      </div>

      {/* Context chips — horizontally scrollable on mobile */}
      <div className="px-6 pb-3 flex items-center gap-2 overflow-x-auto no-scrollbar flex-nowrap sm:flex-wrap">
        {[
          { id: 'general', label: '🌐 General' },
          { id: 'portfolio', label: '📊 Portfolio' },
          { id: 'watchlist', label: '👀 Watchlist' },
          { id: 'market', label: '📈 Market' },
        ].map(c => (
          <button key={c.id} onClick={() => toggleContext(c.id)}
            className={`px-3 py-1 rounded-full text-xs font-medium transition-colors border ${
              contexts.includes(c.id)
                ? 'bg-amber-500/20 border-amber-500/40 text-amber-400'
                : 'bg-white/5 border-white/10 text-gray-500 hover:text-gray-300'
            }`}>
            {c.label}
          </button>
        ))}
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-6 pb-4 space-y-4">
        {showWelcome && (
          <div className="flex flex-col items-center py-12 text-center">
            <div className="text-5xl mb-4">🧠</div>
            <h3 className="text-xl font-bold text-white mb-2">Oracle AI Assistant</h3>
            <p className="text-gray-500 text-sm mb-8 max-w-md">Ask about your portfolio, market trends, or investment strategies. Toggle context chips to include your data.</p>

            {/* Quick Actions — 2 col mobile, 3 col desktop */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 w-full max-w-2xl mb-6">
              {[
                { type: 'portfolio', emoji: '📊', label: 'Portfolio Review' },
                { type: 'watchlist', emoji: '👀', label: 'Watchlist Signals' },
                { type: 'risk', emoji: '🛡️', label: 'Risk & Correlation' },
                { type: 'strategy', emoji: '🎯', label: 'Strategy Advisor' },
                { type: 'onboarding', emoji: '🚀', label: 'Build My Portfolio' },
              ].map(a => (
                <button key={a.type} onClick={() => quickAction(a.type)}
                  className="flex items-center gap-2 p-3 bg-gradient-to-br from-[#1a1d29] to-[#14161f] border border-white/10 rounded-xl text-left text-sm text-gray-300 hover:border-blue-500/30 hover:text-white transition-all">
                  <span className="text-xl">{a.emoji}</span>
                  <span>{a.label}</span>
                </button>
              ))}
              {/* Position Deep Dive */}
              <button onClick={() => { setInput('Analyze $'); setTimeout(() => inputRef.current?.focus(), 50); }}
                className="flex items-center gap-2 p-3 bg-gradient-to-br from-[#1a1d29] to-[#14161f] border border-white/10 rounded-xl text-left text-sm text-gray-300 hover:border-blue-500/30 hover:text-white transition-all">
                <span className="text-xl">🔍</span>
                <span>Position Deep Dive</span>
              </button>
            </div>
          </div>
        )}

        {messages.map(msg => (
          <MessageBubble key={msg.id} msg={msg} onAction={executeAction} onPdf={(c) => exportAsPdf(c)} />
        ))}

        {/* Follow-up suggestions */}
        {suggestions.length > 0 && !streaming && (
          <div className="flex flex-wrap gap-2 pt-2">
            {suggestions.map((s, i) => (
              <button key={i} onClick={() => { setSuggestions([]); send(s); }}
                className="px-3 py-1.5 bg-white/5 border border-white/10 rounded-lg text-gray-400 hover:text-white hover:bg-white/10 text-sm transition-colors">
                {s}
              </button>
            ))}
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input area */}
      <div className="px-6 pb-6">
        <div className="relative bg-gradient-to-br from-[#1a1d29] to-[#14161f] rounded-xl border border-white/10 p-4 flex items-end gap-3">
          <textarea ref={inputRef} value={input} onChange={e => handleInputChange(e.target.value)}
            onKeyDown={handleKey} placeholder="Ask Oracle anything… ($AAPL for ticker autocomplete)"
            rows={1} disabled={streaming}
            className="flex-1 bg-transparent text-white placeholder-gray-600 text-sm resize-none focus:outline-none min-h-[24px] max-h-32 overflow-y-auto disabled:opacity-50"
            style={{ lineHeight: '1.5' }}
          />
          {/* Ticker dropdown */}
          {tickerDropdownOpen && tickerResults.length > 0 && (
            <div className="absolute bottom-full left-4 right-4 mb-2 bg-[#0d0f14] border border-white/10 rounded-xl overflow-hidden shadow-xl z-10">
              {tickerResults.map(t => (
                <button key={t.symbol} onClick={() => insertTicker(t.symbol)}
                  className="w-full flex items-center gap-3 px-4 py-2.5 hover:bg-white/5 transition-colors text-left">
                  <span className="text-white font-mono text-sm font-semibold">{t.symbol}</span>
                  <span className="text-gray-500 text-xs truncate">{t.name}</span>
                </button>
              ))}
            </div>
          )}
          {/* Voice button */}
          {voiceRef.current && (
            <button onClick={toggleVoice} title={listening ? 'Stop listening' : 'Voice input'}
              className={`flex-shrink-0 w-9 h-9 flex items-center justify-center rounded-lg transition-all ${
                listening ? 'bg-red-500 animate-pulse text-white' : 'bg-white/5 text-gray-500 hover:text-white hover:bg-white/10'
              }`}>
              {listening ? <MicOff className="w-4 h-4" /> : <Mic className="w-4 h-4" />}
            </button>
          )}
          <button onClick={() => send()} disabled={streaming || !input.trim()}
            className="flex-shrink-0 w-9 h-9 flex items-center justify-center bg-gradient-to-r from-blue-500 to-purple-600 rounded-lg text-white shadow-lg hover:shadow-blue-500/50 transition-all disabled:opacity-40 disabled:cursor-not-allowed">
            <Send className="w-4 h-4" />
          </button>
        </div>
        <p className="text-gray-600 text-xs mt-2 text-center">Oracle uses your configured AI provider. Always verify financial information independently.</p>
      </div>
    </div>
  );
}
